"""
Searches each BDC's most recent 10-K for mentions of banks from our
bank-side dataset - candidate real edges to seed Phase 3's network
reconstruction, rather than relying purely on marginal totals.

v2: searches for the top ~100 banks by NDFI exposure (generated by
generate_bank_search_list.py) instead of a hand-picked list of 16, plus a
small set of major foreign-bank branches that don't file Call Reports.
RSSD ids are attached directly to each match at search time, since the
search list already carries them - no separate fuzzy-matching step needed
downstream.

Overlap handling: some search terms are substrings of other, different
banks' names (e.g. "City National Bank" is a substring of "City National
Bank Of Florida" - confirmed via generate_bank_search_list.py's collision
detector). When multiple different banks' patterns match overlapping text,
we keep only the longest match and discard shorter ones contained within
it, so a mention of the longer bank's name doesn't get double-counted as
also mentioning the shorter, different bank.

This is still fundamentally a heuristic candidate-generator, not ground
truth: a bank name appearing near "credit facility" / "lender" / "agent"
language is suggestive of a real lending relationship, not proof of one.

Usage:
    python -m app.data_pipeline.sec_edgar.extract_named_lenders --inspect 1287750
    python -m app.data_pipeline.sec_edgar.extract_named_lenders
"""
import argparse
import csv
import re
import time
from pathlib import Path

import requests
from bs4 import BeautifulSoup

MASTER_LIST_PATH = Path(__file__).parent.parent / "raw" / "sec_edgar" / "bdc_master_list.csv"
BANK_SEARCH_TERMS_PATH = Path(__file__).parent.parent / "processed" / "bank_search_terms.csv"
OUT_PATH = Path(__file__).parent.parent / "processed" / "named_lender_candidates.csv"

REQUEST_DELAY_SECONDS = 0.3

# Major foreign-bank branches - real NBFI lenders, but they file FFIEC 002
# (a form for branches of foreign banks) rather than a standard Call Report,
# so they have no RSSD-based node in our bank-side dataset.
FOREIGN_BRANCH_PATTERNS = {
    "SMBC (foreign branch)": [r"Sumitomo Mitsui", r"\bSMBC\b"],
    "MUFG (foreign branch)": [r"MUFG", r"Mitsubishi UFJ"],
    "BNP Paribas (foreign branch)": [r"BNP Paribas"],
    "Deutsche Bank (foreign branch)": [r"Deutsche Bank"],
}

CONTEXT_KEYWORDS = re.compile(r"credit facility|revolving|lender|administrative agent|syndicate|term loan", re.IGNORECASE)


def load_bank_patterns() -> list[dict]:
    """Returns a list of {label, rssd_id, pattern (compiled regex)} for
    every bank we search for - the generated top-N list plus foreign
    branches. Regex special characters in search terms (periods, parens -
    e.g. "U.S. Bank", "Mizuho Bank (Usa)") are escaped so they match
    literally rather than being interpreted as regex syntax."""
    patterns = []

    with BANK_SEARCH_TERMS_PATH.open() as f:
        for row in csv.DictReader(f):
            patterns.append({
                "label": row["bank_name"],
                "rssd_id": row["rssd_id"],
                "search_term": row["search_term"],
                "regex": re.compile(re.escape(row["search_term"]), re.IGNORECASE),
            })

    for label, terms in FOREIGN_BRANCH_PATTERNS.items():
        for term in terms:
            patterns.append({
                "label": label,
                "rssd_id": "",
                "search_term": term,
                "regex": re.compile(term, re.IGNORECASE),
            })

    return patterns


def get_latest_10k(cik: str, user_agent: str) -> dict | None:
    url = f"https://data.sec.gov/submissions/CIK{cik.zfill(10)}.json"
    resp = requests.get(url, headers={"User-Agent": user_agent}, timeout=30)
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    data = resp.json()

    recent = data.get("filings", {}).get("recent", {})
    forms = recent.get("form", [])
    # Prefer the original 10-K over an amendment, which is often a narrow
    # fix (e.g. Part III governance info) and would miss the full
    # financial statements.
    for i, form in enumerate(forms):
        if form == "10-K":
            return {
                "accession": recent["accessionNumber"][i],
                "document": recent["primaryDocument"][i],
                "filed": recent["filingDate"][i],
                "form": form,
            }
    for i, form in enumerate(forms):
        if form == "10-K/A":
            return {
                "accession": recent["accessionNumber"][i],
                "document": recent["primaryDocument"][i],
                "filed": recent["filingDate"][i],
                "form": form,
            }
    return None


def fetch_filing_text(cik: str, accession: str, document: str, user_agent: str) -> str:
    accession_nodash = accession.replace("-", "")
    cik_nopad = str(int(cik))
    url = f"https://www.sec.gov/Archives/edgar/data/{cik_nopad}/{accession_nodash}/{document}"
    resp = requests.get(url, headers={"User-Agent": user_agent}, timeout=60)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "lxml")
    return soup.get_text(separator=" ")


def find_bank_mentions(text: str, bank_patterns: list[dict]) -> list[dict]:
    """Finds all bank mentions near lending-related keywords, resolving
    overlapping matches from different banks by keeping only the longest."""
    raw_matches = []
    for bank in bank_patterns:
        for m in bank["regex"].finditer(text):
            start, end = m.start(), m.end()
            window = text[max(0, start - 100):end + 100]
            if CONTEXT_KEYWORDS.search(window):
                raw_matches.append({
                    "start": start, "end": end,
                    "label": bank["label"], "rssd_id": bank["rssd_id"],
                    "context": " ".join(window.split()),
                })

    # Longest-match-wins: sort longest first, greedily keep matches whose
    # span doesn't overlap one already kept.
    raw_matches.sort(key=lambda m: m["end"] - m["start"], reverse=True)
    kept = []
    covered_ranges = []
    for m in raw_matches:
        overlaps = any(m["start"] < r_end and m["end"] > r_start for r_start, r_end in covered_ranges)
        if not overlaps:
            kept.append(m)
            covered_ranges.append((m["start"], m["end"]))

    kept.sort(key=lambda m: m["start"])
    return kept


def inspect_one(cik: str, user_agent: str):
    bank_patterns = load_bank_patterns()
    print(f"Loaded {len(bank_patterns)} bank search patterns ({len(set(b['label'] for b in bank_patterns))} distinct banks).\n")

    filing = get_latest_10k(cik, user_agent)
    if not filing:
        print(f"No 10-K found for CIK {cik}")
        return

    print(f"Latest 10-K: {filing}")
    url = f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{filing['accession'].replace('-', '')}/{filing['document']}"
    print(f"URL: {url}\n")

    text = fetch_filing_text(cik, filing["accession"], filing["document"], user_agent)
    print(f"Document text length: {len(text):,} characters\n")

    matches = find_bank_mentions(text, bank_patterns)
    print(f"Found {len(matches)} bank mentions near lending-related keywords (after overlap resolution):\n")
    for m in matches[:30]:
        rssd_note = f"RSSD {m['rssd_id']}" if m["rssd_id"] else "no RSSD (foreign branch)"
        print(f"  [{m['label']} - {rssd_note}] ...{m['context']}...\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inspect", metavar="CIK", help="Test against a single CIK first")
    args = parser.parse_args()

    from app.core.config import get_settings
    settings = get_settings()

    if args.inspect:
        inspect_one(args.inspect, settings.sec_edgar_user_agent)
        return

    bank_patterns = load_bank_patterns()
    print(f"Loaded {len(bank_patterns)} bank search patterns ({len(set(b['label'] for b in bank_patterns))} distinct banks).\n")

    with MASTER_LIST_PATH.open() as f:
        bdcs = list(csv.DictReader(f))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["bdc_cik", "bdc_name", "bank_matched", "rssd_id", "context", "source_filing_date"]

    with OUT_PATH.open("w", newline="") as out_f:
        writer = csv.DictWriter(out_f, fieldnames=fieldnames)
        writer.writeheader()

        total_candidates = 0
        for i, bdc in enumerate(bdcs, start=1):
            cik, name = bdc["cik"], bdc["name"]
            print(f"[{i}/{len(bdcs)}] {name} ({cik}) ...")

            try:
                filing = get_latest_10k(cik, settings.sec_edgar_user_agent)
                if not filing:
                    print("  No 10-K found")
                    continue
                text = fetch_filing_text(cik, filing["accession"], filing["document"], settings.sec_edgar_user_agent)
                matches = find_bank_mentions(text, bank_patterns)
                for m in matches:
                    writer.writerow({
                        "bdc_cik": cik, "bdc_name": name,
                        "bank_matched": m["label"], "rssd_id": m["rssd_id"],
                        "context": m["context"], "source_filing_date": filing["filed"],
                    })
                    total_candidates += 1
                out_f.flush()
                if matches:
                    print(f"  Found {len(matches)} candidate mentions")
            except requests.HTTPError as e:
                print(f"  ERROR: {e}")
            except Exception as e:
                print(f"  UNEXPECTED ERROR: {e}")

            time.sleep(REQUEST_DELAY_SECONDS)

    print(f"\nWrote {total_candidates} candidate lender mentions to {OUT_PATH}")


if __name__ == "__main__":
    main()